CREATE TYPE Role AS ENUM ('Merchant', 'Customer');

CREATE TABLE users (
	id SERIAL PRIMARY KEY, 	
	FirstName TEXT NOT NULL, 
	LastName TEXT NOT NULL, 
	phone VARCHAR NOT NULL UNIQUE, 
	email VARCHAR NOT NULL UNIQUE, 
	passwords VARCHAR(255) NOT NULL,
	role Role NOT NULL DEFAULT 'Customer',
	salt VARCHAR(255) NOT NULL
);